title: Finance Budget Tool
theme: jekyll-theme-primer

# Prevent Jekyll from reading build artifacts or Node modules
exclude:
  - node_modules
  - frontend/node_modules
  - backend/node_modules
  - frontend/package.json
  - backend/package.json
  - frontend/package-lock.json
  - backend/package-lock.json
  - README.md
  - LICENSE
