name: Build and Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - master   # or 'main' if your default branch is main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup Node.js 20 (required for Vite)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm ci

      # 4. Build frontend using Vite
      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build

      # 5. Upload build folder as Pages artifact
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist  # Vite default build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
